# Generated by Django 3.2.5 on 2021-07-02 08:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, help_text='choose type of pet', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_pets',
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(blank=True, help_text="country's fish", max_length=255, null=True)),
                ('name', models.CharField(blank=True, help_text="fish's name", max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, default=datetime.datetime(2021, 7, 2, 8, 0, 49, 709728, tzinfo=utc), help_text='birth of day', null=True)),
                ('color', models.CharField(blank=True, help_text="fish's color", max_length=255, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, help_text="fish's price", null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fish', to='pet.pets')),
            ],
            options={
                'db_table': 'tbl_fish',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(blank=True, help_text="country's dog", max_length=255, null=True)),
                ('name', models.CharField(blank=True, help_text="dog's name", max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, default=datetime.datetime(2021, 7, 2, 8, 0, 49, 708728, tzinfo=utc), help_text='birth of day', null=True)),
                ('color', models.CharField(blank=True, help_text="dog's color", max_length=255, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, help_text="dog's price", null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dog', to='pet.pets')),
            ],
            options={
                'db_table': 'tbl_dog',
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(blank=True, help_text="country's cat", max_length=255, null=True)),
                ('name', models.CharField(blank=True, help_text="cat's name", max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, default=datetime.datetime(2021, 7, 2, 8, 0, 49, 707728, tzinfo=utc), help_text='birth of day', null=True)),
                ('color', models.CharField(blank=True, help_text="cat's color", max_length=255, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, help_text="cat's price", null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cat', to='pet.pets')),
            ],
            options={
                'db_table': 'tbl_cat',
            },
        ),
    ]
