# Generated by Django 3.2.5 on 2021-07-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birthday',
            field=models.DateField(blank=True, help_text='birth of day', null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='birthday',
            field=models.DateField(blank=True, help_text='birth of day', null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='birthday',
            field=models.DateField(blank=True, help_text='birth of day', null=True),
        ),
    ]
